# Generated by Django 3.1.5 on 2021-01-21 17:36

from django.db import migrations, models
import entries.models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='entry_text',
            field=models.TextField(blank=True, verbose_name='tekst'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='entry_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='tytul'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=entries.models.upload_path),
        ),
    ]
