# Generated by Django 3.1.5 on 2021-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20210203_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_title',
            field=models.TextField(blank=True, verbose_name='tytul'),
        ),
    ]
