# Generated by Django 3.1.5 on 2021-02-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_comments_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='comments',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='entries.comments'),
        ),
    ]
