# Generated by Django 3.1.5 on 2021-02-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_entries_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.comments'),
        ),
    ]
