# Generated by Django 3.1.5 on 2021-02-03 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20210203_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entries.comments'),
        ),
    ]
