# Generated by Django 3.1.5 on 2021-02-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_remove_entries_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.comments'),
        ),
    ]
