# Generated by Django 3.1.5 on 2021-02-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_entries_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entries'),
        ),
    ]
