# Generated by Django 3.1.5 on 2021-02-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20210204_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='users',
            new_name='comment_author',
        ),
    ]
